defmodule Tunez.Repo.Migrations.UpdateAlbumCoverName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:albums), :cover_img_url, to: :cover_image_url
  end

  def down do
    rename table(:albums), :cover_image_url, to: :cover_img_url
  end
end
