defmodule Tunez.Repo.Migrations.UpdateAlbumProperyName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:albums), :year_release, to: :year_released
  end

  def down do
    rename table(:albums), :year_released, to: :year_release
  end
end
